### ISSUE TITLE
Truncate line drawing for short blocks

### ISSUE THREAD

**Issue by aarctan** [aarctan/schedubuddy-web#53]
In the case below, truncate everything after the course name and section information, e.g. everything other than GEOPH 521 and SEM J01 (40128).
![image](https://user-images.githubusercontent.com/83198532/218290006-3bcdb4d6-0f68-47b5-947c-1dadf60fb47f.png)

**Comment by Exanut** [comment]
It would be nice to truncate based off an early calculation of how many lines may fit in the vertical length of the block.

**Comment by aarctan** [comment]
64cedf6e8c7333d928498b44f7a479498e2313b8
