### ISSUE TITLE
HTML parsing is returning undefined for professor names

### ISSUE THREAD

**Issue by dylandeco** [aarctan/schedubuddy-web#57]
When there is a middle name for the professor, it is making it so the last name is not getting parsed properly and is resulting in UNDEFINED showing in the class block on the schedule

![schedubudy_undefined](https://user-images.githubusercontent.com/69830467/218922488-325ee1ea-aa9e-4a89-8ea0-cc8bab9660a0.PNG)

**Comment by Exanut** [comment]
It is possible for this to be band-aid fixed in the front end but since the api is not giving expected output I'll assign to myself

**Comment by aarctan** [comment]
Fixed in the backend. Although now only the first instructor will be displayed, so no co-instructors, assistant instructors, or multiple primary instructors.
