### ISSUE TITLE
suggestion - lock schedule blocks in place

### ISSUE THREAD

**Issue by Mattwmaster58** [aarctan/schedubuddy-web#64]
From @AidenKly 

I would like to suggest the ability to lock certain classes in place and only show full schedule results that have a certain class at a certain time. For example:

I want to take courses A,B,C and D this term. The schedule builder spits out 30+ results. I want to be able to narrow that down after being shown the schedules to only the schedules that have class A at 10:00 AM.

**Comment by Mattwmaster58** [comment]
Some considerations, it may make sense to split locking the each component of a class. IE, lock the lecture down but not the lab, etc

**Comment by aarctan** [comment]
We need an intuitive UI for this feature that can respect aliases and also large search spaces. It's probably best to add this to an advanced options section and have a form for each course selected to enable locking of each component.

**Comment by aarctan** [comment]
I extended this feature request to include both whitelisting and blacklisting, as toggles for all classes that a course can have. For now, aliased classes need to be handled by the user. 

As it's a part of the website now, please make another issue for anything related to this. Thanks for suggesting and hopefully this is useful.
