### ISSUE TITLE
feature request: should list prof names if available for class components

### ISSUE THREAD

**Issue by Mattwmaster58** [aarctan/schedubuddy-web#71]
![image](https://github.com/aarctan/schedubuddy-web/assets/26337069/de93968d-5c20-4ad1-903a-2f22ca0f5872)
ex, would be nice to know here which profs were who

**Comment by aarctan** [comment]
In the tooltip?

**Comment by aarctan** [comment]
This can get cluttered if they are shown with the sections (A1 etc). https://github.com/aarctan/schedubuddy-web/commit/c9281211d2229e1f0210ffc4cedcb17d59b2a5e0 will show in the tooltip for now.
