### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by ZHIYUA15** [aarctan/schedubuddy-web#77]
Site Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on Netlify.

[Back to our site](https://schedubuddy.com/)

If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's ["page not found" support guide](https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125?utm_source=404page&utm_campaign=community_tracking) for troubleshooting tips.

Netlify Internal ID: 01HAXGAB6XCDRFTB0GVBFMDGG1

**Comment by aarctan** [comment]
Sadly Im no longer hosting the website. I've realized this type of app is better maintained by current students and who might benefit from the experience, which doesn't apply to alumni like me anymore. The repos will remain open as a reference for students interested in creating the next iteration of uofa schedule generators :)

**Comment by ZHIYUA15** [comment]
oh damn bro, schedulebuudy is useful and gives a lot of convenience.
Since I didn't take any Web design courses but mostly hardware computer, I
wonder who is gonna takeover schedulebuddy website rn.

Also, I can pay the domain cost and other costs for maintaining this
website, or do you have any instructions for using the given repository by
our own to make the website works in our local machine maybe?

Sincerely,
Zhiyuan L.

**Comment by kiankyars** [comment]
> Sadly Im no longer hosting the website. I've realized this type of app is better maintained by current students and who might benefit from the experience, which doesn't apply to alumni like me anymore. The repos will remain open as a reference for students interested in creating the next iteration of uofa schedule generators :)

How did you deploy the website @aarctan ?

**Comment by aarctan** [comment]
I got a lot of questions about what happened to the site, and felt bad about others' contributions going to waste. I've brought it back online, at least until the domain expires in May 2024. Then I'll seek to pass on ownership and provide docs or steps to run locally.
