### ISSUE TITLE
BUG: Adding new class to scheduler after filtering out another class crashes app

### ISSUE THREAD

**Issue by httaq** [aarctan/schedubuddy-web#79]
To reproduce:
- Select a course in Scheduler
- Select a section to filter out in Advanced
- Add another course

App crashes as soon as new course is selected from drop down.

Cause:
In `CourseLock`, once a section has been filtered out, `Object.keys(values.blacklist).length > 0` will be true, affecting the initial state of `isEnabled` for subsequent courses.
Since `isEnabled` is now true, `Object.keys(props.data).map(...)` will be evaluated even though `data` is not fetched yet. 

Possible fix:
`  const [isEnabled, setIsEnabled] = useState(false);`

**Comment by aarctan** [comment]
Thanks for investigating this. I think your proposed fix will work, would you be interested in making a merge request for the credit?

**Comment by httaq** [comment]
Sure I'd be happy to.
