### ISSUE TITLE
auto select the current term 

### ISSUE THREAD

**Issue by Mattwmaster58** [aarctan/schedubuddy-web#84]
For occupancy finder, default being current term makes sense.

For schedule planner, default being the next term unless before drop deadline makes sense. First day of classes + 2w I think is a good heuristic.

**Comment by httaq** [comment]
Nice idea but for planner I think there's too many exceptions to the heuristics (honors math, education, Augustana etc.)

**Comment by aarctan** [comment]
I thought about this a while ago too. It makes sense for occupancy viewer/finder but since the remaining fields need to be entered anyway, I'm not sure this is worth it. If they are selecting the term themselves they can see it's not a fixed field either. Will close for now
